receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  # elasticsearch:
  #   endpoints: [http://elasticsearch:9200]
  #   traces_index: trace_index
  #   tls:
  #     insecure: true
  jaeger:
    endpoint: jaeger-collector:14250
    tls:
      insecure: true

  logging:

  # jaeger:
  #   endpoint: jaeger-all-in-one:14250
  #   tls:
  #     insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger,logging]
    logs:
      receivers: [otlp]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]