apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-title
  labels:
    service: title
spec:
  replicas: 1
  selector:
    matchLabels:
      service: title
  template:
    metadata:
      labels:
        service: title
    spec:
      containers:
        - name: main
          image: {{ .Values.title.image.repository }}:{{ .Values.title.image.tag }}
          ports:
          - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4317
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
