apiVersion: v1
kind: Service
metadata:
  name: service-title
  labels:
    service: title
spec:
  type: ClusterIP
  selector:
    service: title
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP