apiVersion: v1
kind: Service
metadata:
  name: service-artist
  labels:
    service: artist
spec:
  type: ClusterIP
  selector:
    service: artist
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP