apiVersion: v1
kind: Service
metadata:
  name: service-price
  labels:
    service: price
spec:
  type: ClusterIP
  selector:
    service: price
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP