apiVersion: apps/v1
kind: Deployment
metadata:
  name: public
  labels:
    service: public
spec:
  replicas: 1
  selector:
    matchLabels:
      service: public
  template:
    metadata:
      labels:
          service: public
    spec:
      containers:
        - name: main
          image: {{ .Values.public.image.repository }}:{{ .Values.public.image.tag }}
          ports:
          - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: SERVICE_ARTIST_URL
              value: http://service-artist:8080
            - name: SERVICE_PRICE_URL
              value: http://service-price:8080
            - name: SERVICE_TITLE_URL
              value: http://service-title:8080
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4317
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
