apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public
  labels:
    service: public
spec:
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: /album
            pathType: Prefix
            backend:
              service:
                name: public
                port:
                  number: 8080
