apiVersion: v1
kind: Service
metadata:
  name: public
  labels:
    service: public
spec:
  type: ClusterIP
  selector:
    service: public
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP